<?php
namespace App\Services;
use App\Models\ActivityLog; use App\Models\Volunteer; use App\Models\VolunteerVisit; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Storage; use Symfony\Component\HttpFoundation\File\UploadedFile; use App\Services\GeographicScopeService;
class VolunteerVisitService {
 public function create(array $data, User $actor, Request $request): VolunteerVisit { return DB::transaction(function() use($data,$actor,$request){ $vol=Volunteer::findOrFail($data['volunteer_id']); abort_unless($actor->hasRole('super-admin')||app(GeographicScopeService::class)->allowsVillage($actor,$vol->village_id,$vol->ward_id),403); $visit=VolunteerVisit::create($data+['created_by'=>$actor->id]); $this->audit($visit,'visit_assigned',$actor,$request); return $visit->load(['volunteer','citizen','family','village','ward','activityLogs']); }); }
 public function update(VolunteerVisit $visit,array $data,User $actor,Request $request): VolunteerVisit { return DB::transaction(function()use($visit,$data,$actor,$request){$old=$visit->getAttributes();if(isset($data['volunteer_id'])){$vol=Volunteer::findOrFail($data['volunteer_id']);abort_unless($actor->hasRole('super-admin')||app(GeographicScopeService::class)->allowsVillage($actor,$vol->village_id,$vol->ward_id),403);}$visit->update($data+['updated_by'=>$actor->id]);$this->audit($visit,'visit_updated',$actor,$request,$old);return $visit->fresh(['volunteer','citizen','family','village','ward','activityLogs']);}); }
 public function checkIn(VolunteerVisit $visit,array $data,User $actor,Request $request): VolunteerVisit { return DB::transaction(function()use($visit,$data,$actor,$request){abort_unless(in_array($visit->status,['assigned','accepted'],true),422,'Visit cannot be checked in from its current status.');$visit->update(['status'=>'checked_in','checked_in_at'=>now(),'check_in_latitude'=>$data['latitude'],'check_in_longitude'=>$data['longitude'],'updated_by'=>$actor->id]);$this->audit($visit,'visit_checked_in',$actor,$request);return $visit->fresh();}); }
 public function complete(VolunteerVisit $visit,array $data,User $actor,Request $request): VolunteerVisit { return DB::transaction(function()use($visit,$data,$actor,$request){abort_unless($visit->status==='checked_in',422,'Visit must be checked in before completion.');$paths=[];foreach($request->file('attachments',[]) as $file){if($file instanceof UploadedFile)$paths[]=$file->store("volunteer-visits/{$visit->id}",'local');}$visit->update(['status'=>'completed','checked_out_at'=>now(),'check_out_latitude'=>$data['latitude'],'check_out_longitude'=>$data['longitude'],'outcome'=>$data['outcome'],'notes'=>$data['notes']??$visit->notes,'follow_up_required'=>$data['follow_up_required']??false,'follow_up_date'=>$data['follow_up_date']??null,'follow_up_notes'=>$data['follow_up_notes']??null,'attachments'=>$paths,'updated_by'=>$actor->id]);$this->audit($visit,'visit_completed',$actor,$request);return $visit->fresh(['volunteer','citizen','family','village','ward','activityLogs']);}); }
 public function deleteAttachment(VolunteerVisit $visit,int $index,User $actor,Request $request): VolunteerVisit { return DB::transaction(function()use($visit,$index,$actor,$request){$paths=$visit->attachments??[];abort_unless(array_key_exists($index,$paths),404);$path=$paths[$index];Storage::disk('local')->delete($path);array_splice($paths,$index,1);$visit->update(['attachments'=>$paths,'updated_by'=>$actor->id]);$this->audit($visit,'visit_attachment_deleted',$actor,$request);return $visit->fresh();}); }
 public function attachmentPath(VolunteerVisit $visit,int $index): string { $paths=$visit->attachments??[];abort_unless(array_key_exists($index,$paths),404);abort_unless(Storage::disk('local')->exists($paths[$index]),404,'Attachment not found.');return $paths[$index]; }
 private function audit(VolunteerVisit $visit,string $action,User $actor,Request $request,?array $old=null):void{ActivityLog::create(['user_id'=>$actor->id,'loggable_type'=>VolunteerVisit::class,'loggable_id'=>$visit->id,'action'=>$action,'module'=>'volunteers','description'=>str_replace('_',' ',$action),'old_values'=>$old,'new_values'=>$visit->getAttributes(),'ip_address'=>$request->ip(),'user_agent'=>$request->userAgent()]);}
}
