<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Http\Requests\Volunteer\{StoreVolunteerVisitRequest,UpdateVolunteerVisitRequest,CheckInVisitRequest,CompleteVolunteerVisitRequest}; use App\Http\Resources\VolunteerVisitResource; use App\Models\Volunteer; use App\Models\VolunteerVisit; use App\Services\VolunteerVisitService; use App\Services\GeographicScopeService; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\Storage; use Symfony\Component\HttpFoundation\StreamedResponse;
class VolunteerVisitController extends Controller {
 public function index(Request $request):JsonResponse { $this->authorize('viewAny',VolunteerVisit::class);$q=VolunteerVisit::with(['volunteer:id,volunteer_id,first_name,last_name,village_id','citizen:id,unique_id,first_name,last_name','family:id,family_id,head_of_family_name','village:id,name','ward:id,name','activityLogs.user:id,name']);$user=$request->user();if($user->hasRole('volunteer')){$q->whereHas('volunteer',fn($v)=>$v->where('user_id',$user->id));}else{$vols=Volunteer::query();app(GeographicScopeService::class)->apply($vols,$user);$q->whereIn('volunteer_id',$vols->select('id'));}if($status=$request->get('status'))$q->where('status',$status);if($type=$request->get('visit_type'))$q->where('visit_type',$type);if($request->filled('volunteer_id'))$q->where('volunteer_id',$request->get('volunteer_id'));if($search=trim((string)$request->get('search')))$q->where(fn($x)=>$x->where('notes','ilike',"%{$search}%")->orWhere('outcome','ilike',"%{$search}%")->orWhereHas('citizen',fn($c)=>$c->where('first_name','ilike',"%{$search}%")->orWhere('last_name','ilike',"%{$search}%")));$sort=in_array($request->get('sort'),['scheduled_at','created_at','checked_out_at'],true)?$request->get('sort'):'scheduled_at';$p=$q->orderBy($sort,$request->get('direction')==='asc'?'asc':'desc')->paginate(min(max((int)$request->get('per_page',20),1),100));return response()->json(['data'=>VolunteerVisitResource::collection($p->getCollection())->resolve(),'meta'=>['total'=>$p->total(),'per_page'=>$p->perPage(),'current_page'=>$p->currentPage(),'last_page'=>$p->lastPage()]]); }
 public function show(Request $request,VolunteerVisit $visit):JsonResponse{$this->authorize('view',$visit);return response()->json((new VolunteerVisitResource($visit->load(['volunteer','citizen','family','village','ward','activityLogs.user:id,name'])))->resolve($request));}
 public function store(StoreVolunteerVisitRequest $request,VolunteerVisitService $service):JsonResponse{return response()->json((new VolunteerVisitResource($service->create($request->validated(),$request->user(),$request)))->resolve($request),201);}
 public function update(UpdateVolunteerVisitRequest $request,VolunteerVisit $visit,VolunteerVisitService $service):JsonResponse{return response()->json((new VolunteerVisitResource($service->update($visit,$request->validated(),$request->user(),$request)))->resolve($request));}
 public function checkIn(CheckInVisitRequest $request,VolunteerVisit $visit,VolunteerVisitService $service):JsonResponse{return response()->json((new VolunteerVisitResource($service->checkIn($visit,$request->validated(),$request->user(),$request)))->resolve($request));}
 public function complete(CompleteVolunteerVisitRequest $request,VolunteerVisit $visit,VolunteerVisitService $service):JsonResponse{return response()->json((new VolunteerVisitResource($service->complete($visit,$request->validated(),$request->user(),$request)))->resolve($request));}
 public function downloadAttachment(Request $request,VolunteerVisit $visit,int $index,VolunteerVisitService $service):StreamedResponse{$this->authorize('view',$visit);return response()->streamDownload(fn()=>readfile(Storage::disk('local')->path($service->attachmentPath($visit,$index))),basename($service->attachmentPath($visit,$index)));}
 public function deleteAttachment(Request $request,VolunteerVisit $visit,int $index,VolunteerVisitService $service):JsonResponse{$this->authorize('update',$visit);return response()->json((new VolunteerVisitResource($service->deleteAttachment($visit,$index,$request->user(),$request)))->resolve($request));}
 public function stats(Request $request):JsonResponse{$this->authorize('viewAny',VolunteerVisit::class);$q=VolunteerVisit::query();$user=$request->user();if($user->hasRole('volunteer'))$q->whereHas('volunteer',fn($v)=>$v->where('user_id',$user->id));else{$vols=Volunteer::query();app(GeographicScopeService::class)->apply($vols,$user);$q->whereIn('volunteer_id',$vols->select('id'));}return response()->json(['assigned'=>(clone$q)->whereIn('status',['assigned','accepted'])->count(),'checked_in'=>(clone$q)->where('status','checked_in')->count(),'completed'=>(clone$q)->where('status','completed')->count(),'missed'=>(clone$q)->where('status','missed')->count(),'follow_up_pending'=>(clone$q)->where('follow_up_required',true)->whereNull('checked_out_at')->count()]);}
}
