<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Http\Requests\Project\SaveProjectLookupRequest; use App\Http\Resources\ProjectLookupResource; use App\Models\{ProjectCategory,ProjectType,ProjectAgency,Department}; use App\Models\ActivityLog; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class ProjectLookupController extends Controller {
 private function model(string $lookup){return match($lookup){ 'category'=>ProjectCategory::class,'type'=>ProjectType::class,'agency'=>ProjectAgency::class,'department'=>Department::class,default=>throw ValidationException::withMessages(['lookup'=>['Unknown project lookup.']])};}
 private function authorizeManage(Request $r):void{abort_unless($r->user()?->hasPermission('projects.manage'),403);}
 public function index(Request $r,string $lookup):JsonResponse{$this->authorizeManage($r);$model=$this->model($lookup);$q=$model::query();if($r->boolean('with_trashed'))$q->withTrashed();if($r->boolean('only_trashed'))$q->onlyTrashed();if($r->filled('search'))$q->where(fn($x)=>$x->where('name','ilike','%'.$r->get('search').'%')->orWhere('code','ilike','%'.$r->get('search').'%'));if($r->filled('is_active'))$q->where('is_active',$r->boolean('is_active'));$sort=in_array($r->get('sort'),['name','code','created_at'],true)?$r->get('sort'):'name';$page=$q->orderBy($sort,$r->get('direction')==='desc'?'desc':'asc')->paginate(min(max((int)$r->get('per_page',20),1),100));return response()->json(['data'=>ProjectLookupResource::collection($page->getCollection())->resolve(),'meta'=>['total'=>$page->total(),'per_page'=>$page->perPage(),'current_page'=>$page->currentPage(),'last_page'=>$page->lastPage()]]);}
 public function store(SaveProjectLookupRequest $request,string $lookup):JsonResponse{$this->authorizeManage($request);$model=$this->model($lookup);$data=$request->validated();if($model::withTrashed()->where('code',$data['code'])->exists())throw ValidationException::withMessages(['code'=>['The code is already in use.']]);$row=DB::transaction(function()use($model,$data,$request,$lookup){$row=$model::create($data+['created_by'=>$request->user()->id]);ActivityLog::create(['user_id'=>$request->user()->id,'loggable_type'=>$model,'loggable_id'=>$row->id,'action'=>'created','module'=>'projects','description'=>"Project {$lookup} created",'new_values'=>$row->getAttributes(),'ip_address'=>$request->ip(),'user_agent'=>$request->userAgent()]);return$row;});return response()->json(ProjectLookupResource::make($row)->resolve(),201);}
 public function update(SaveProjectLookupRequest $request,string $lookup,string $id):JsonResponse{$this->authorizeManage($request);$model=$this->model($lookup);$row=$model::findOrFail($id);$data=$request->validated();if($model::withTrashed()->where('code',$data['code'])->where('id','!=',$id)->exists())throw ValidationException::withMessages(['code'=>['The code is already in use.']]);$old=$row->getAttributes();DB::transaction(function()use($row,$data,$request,$model,$lookup,$old){$row->update($data+['updated_by'=>$request->user()->id]);ActivityLog::create(['user_id'=>$request->user()->id,'loggable_type'=>$model,'loggable_id'=>$row->id,'action'=>'updated','module'=>'projects','description'=>"Project {$lookup} updated",'old_values'=>$old,'new_values'=>$row->fresh()->getAttributes(),'ip_address'=>$request->ip(),'user_agent'=>$request->userAgent()]);});return response()->json(ProjectLookupResource::make($row->fresh())->resolve());}
 public function destroy(Request $r,string $lookup,string $id):JsonResponse{$this->authorizeManage($r);$model=$this->model($lookup);$row=$model::findOrFail($id);abort_if($row->projects()->exists(),409,'This lookup is in use by projects.');$row->delete();return response()->json(['message'=>'Lookup deleted.']);}
 public function restore(Request $r,string $lookup,string $id):JsonResponse{$this->authorizeManage($r);$model=$this->model($lookup);$row=$model::onlyTrashed()->findOrFail($id);$row->restore();return response()->json(ProjectLookupResource::make($row)->resolve());}
}
